# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: 
  vmImage: ubuntu-latest

name: Build_$(Build.BuildId)

stages:
- template: pipeline-templates8/stages/build.yml
- template: pipeline-templates8/stages/deploy-dev.yml
- template: pipeline-templates8/stages/smoke-test-dev.yml
- template: pipeline-templates8/stages/deploy-uat.yml
- template: pipeline-templates8/stages/smoke-test-uat.yml
- template: pipeline-templates8/stages/deploy-preprod.yml
- template: pipeline-templates8/stages/smoke-test-preprod.yml
- template: pipeline-templates8/stages/deploy-prod.yml
- template: pipeline-templates8/stages/smoke-test-prod.yml

  # parameters:
  #     AdminPassword: $(AdminPassword)
  #     AdminTestPassword: $(AdminTestPassword)
  #     HostingPlan: $(HostingPlan)
  #     ServerName: $(ServerName)
  #     WebsiteName: $(WebsiteName)
