stages:
- stage: Build_Test_Stage
  displayName: Build & Test Stage
  jobs:
  - template: ../jobs/include-jfrog.yml
  - template: ../jobs/include-tools.yml
  - template: ../jobs/include-npm-steps.yml
  - template: ../jobs/include-artifact-steps.yml