stages:
- stage: Deploy_DEV_Stage
  displayName: Deploy DEV Stage
  dependsOn: Build_Test_Stage
  jobs:
  - deployment: Deploy_DEV
    variables:
      MyVersion: Build_$(Build.BuildId)
    displayName: $(MyVersion)
    pool:
      vmImage: ubuntu-latest
    # creates an environment if it doesn't exist
    environment: 'BrokerAdapter'
    strategy:
      # default deployment strategy, more coming...
      runOnce:
        deploy:
          steps:
          - script: echo my first deployment