stages:
- stage: Smoke_Test_DEV_Stage
  displayName: Smoke Test DEV Stage
  dependsOn: Deploy_DEV_Stage
  jobs:
  - job: PostSubmission_Test
    displayName: Post Submission Test
    steps:
    - script: echo I am CD Stage
      displayName: Run a one-line script2
  - job: PostBoundOffer_Test
    displayName: Post Bound Offer Test
    steps:
    - script: echo I am CD Stage
      displayName: Run a one-line script2