stages:
- stage: CD_DEV
  displayName: CD DEV
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    # creates an environment if it doesn't exist
    environment: 'DEV'
    strategy:
      # default deployment strategy, more coming...
      runOnce:
        deploy:
          steps:
          - script: echo my first deployment