stages:
- stage: CD_PROD
  displayName: CD PROD
  jobs:
  - deployment: Deploy_PROD
    displayName: Deploy PROD
    pool:
      vmImage: ubuntu-latest
    # creates an environment if it doesn't exist
    environment: 'PROD'
    strategy:
      # default deployment strategy, more coming...
      runOnce:
        deploy:
          steps:
          - script: echo my first deployment