stages:
- stage: CD_PREPROD
  displayName: CD PREPROD
  jobs:
  - deployment: Deploy_PREPROD
    displayName: Deploy PREPROD
    pool:
      vmImage: ubuntu-latest
    # creates an environment if it doesn't exist
    environment: 'PREPROD'
    strategy:
      # default deployment strategy, more coming...
      runOnce:
        deploy:
          steps:
          - script: echo my first deployment