stages:
- stage: CD_UAT
  displayName: CD UAT
  jobs:
  - deployment: Deploy_UAT
    displayName: Deploy UAT
    pool:
      vmImage: ubuntu-latest
    # creates an environment if it doesn't exist
    environment: 'UAT'
    strategy:
      # default deployment strategy, more coming...
      runOnce:
        deploy:
          steps:
          - script: echo my first deployment